version: '3'
services:
  influxdb:
    build:
      context: config/influxdb/
    container_name: influxdb
    ports:
      - 8086:8086
      - 8083:8083
      - 8090:8090
    volumes:
      - influxdb_data:/usr/share/influxdb/data
  telegraf:
    build:
      context: config/telegraf/
    container_name: telegraf
    ports:
      - 8092:8092
      - 8094:8094
    depends_on:
      - influxdb
  chronograf:
    build:
      context: config/chronograf
    container_name: chronograf
    ports:
      - 8888:8888
    volumes:
      - chronograf_data:/var/lib/chronograf
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
volumes:
  influxdb_data:
    driver: local
  chronograf_data:
    driver: local